#!/usr/bin/env python3
"""
Install Git pre-commit hook.

This script installs a Git pre-commit hook that automatically updates context before each commit.
"""

import os
import sys
import shutil
from pathlib import Path


def get_hook_path() -> Path:
    """Get Git hooks directory."""
    current = Path.cwd()
    while current != current.root:
        git_dir = current / '.git'
        if git_dir.exists() and git_dir.is_dir():
            return git_dir / 'hooks'
        current = current.parent

    return None


def install_hook(hooks_dir: Path, script_path: Path):
    """Install pre-commit hook."""

    if not hooks_dir.exists():
        print(f"❌ Error: Git hooks directory not found at {hooks_dir}")
        sys.exit(1)

    hook_path = hooks_dir / 'pre-commit'

    if hook_path.exists():
        backup_path = hooks_dir / 'pre-commit.backup'
        shutil.copy(hook_path, backup_path)
        print(f"⚠️  Existing pre-commit hook backed up to {backup_path}")

    hook_content = f"""#!/bin/bash
# Auto-generated by codebase-context-manager

echo "🔄 Updating codebase context..."

# Get staged source files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(py|js|ts|jsx|tsx|go|java|rs|rb|php|swift|kt|scala)$' || true)

if [ -n "$STAGED_FILES" ]; then
    echo "📝 Detected staged source files, updating context..."

    cd "$(git rev-parse --show-toplevel)"
    python3 {script_path} --headers-only --no-parent

    git add $(echo "$STAGED_FILES" | tr '\\n' ' ')
fi

echo "✅ Codebase context updated"
"""

    with open(hook_path, 'w') as f:
        f.write(hook_content)

    os.chmod(hook_path, 0o755)

    print(f"✅ Git pre-commit hook installed at {hook_path}")
    print("\n📝 The hook will automatically update file headers when you commit source files.")


def main():
    """Main function."""
    import argparse

    parser = argparse.ArgumentParser(description='Install Git pre-commit hook for codebase context')
    parser.add_argument('--uninstall', action='store_true', help='Remove the installed hook')
    parser.add_argument('--script-path', help='Path to update_context.py script')

    args = parser.parse_args()

    hooks_dir = get_hook_path()

    if hooks_dir is None:
        print("❌ Error: Not in a Git repository")
        sys.exit(1)

    if args.uninstall:
        hook_path = hooks_dir / 'pre-commit'

        if not hook_path.exists():
            print("⚠️  No pre-commit hook found")
            sys.exit(0)

        with open(hook_path, 'r') as f:
            content = f.read()
            if 'codebase-context-manager' not in content:
                print("⚠️  Existing pre-commit hook was not installed by codebase-context-manager")
                print("   To remove it anyway, manually delete: {}".format(hook_path))
                sys.exit(1)

        os.remove(hook_path)
        print("✅ Git pre-commit hook uninstalled")

        backup_path = hooks_dir / 'pre-commit.backup'
        if backup_path.exists():
            shutil.copy(backup_path, hook_path)
            os.remove(backup_path)
            print("✅ Previous hook restored from backup")

        sys.exit(0)

    if args.script_path:
        script_path = Path(args.script_path)
    else:
        script_path = Path(__file__).parent / 'update_context.py'

    if not script_path.exists():
        print(f"❌ Error: Script not found at {script_path}")
        sys.exit(1)

    script_path = script_path.resolve()

    install_hook(hooks_dir, script_path)


if __name__ == '__main__':
    main()
